export const POST_USER_SUCCESS = 'POST_USER_SUCCESS'
export const POST_USER_FALIURE = 'POST_USER_FALIURE'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FALIURE = 'FETCH_USER_FALIURE'