export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAILURE = "GET_DATA_FAILURE";

/* export const GET_STREETFOOD_REQUEST = "GET_STREETFOOD_REQUEST";
export const GET_STREETFOOD_SUCCESS = "GET_STREETFOOD_SUCCESS";
export const GET_STREETFOOD_FAILURE = "GET_STREETFOOD_FAILURE"; */

export const ADD_CART_REQUEST = "ADD_CART_REQUEST";
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const ADD_CART_FAILURE = "ADD_CART_FAILURE";